INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('951308841', 'Networked hybrid functionalities', 'night', '13');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('556944619', 'Diverse 4th generation infrastructure', 'night', '32');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('905210890', 'Up-sized encompassing instruction set', 'day', '9');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('685693187', 'Centralized cohesive contingency', 'day', '96');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('355518275', 'Implemented mobile paradigm', 'night', '48');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('690999812', 'Customizable real-time core', 'night', '69');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('572428870', 'Polarised intermediate extranet', 'day', '23');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('377178008', 'Reverse-engineered uniform data-warehouse', 'night', '93');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('9955676', 'Customizable transitional firmware', 'night', '61');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('432988112', 'Grass-roots web-enabled encryption', 'day', '76');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('23233577', 'Enhanced 24/7 task-force', 'day', '16');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('655297976', 'Progressive zero tolerance synergy', 'day', '33');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('16595030', 'Cross-group systematic approach', 'day', '4');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('418590525', 'Intuitive impactful help-desk', 'night', '7');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('114639314', 'Multi-layered static collaboration', 'day', '10');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('777309245', 'Compatible fresh-thinking methodology', 'night', '10');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('442065685', 'Face to face fresh-thinking capacity', 'day', '8');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('597799175', 'Optimized web-enabled secured line', 'night', '2');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('696030547', 'Public-key national infrastructure', 'day', '5');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('715513161', 'Persevering tangible monitoring', 'day', '85');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('240315758', 'Pre-emptive systematic moderator', 'night', '54');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('696844430', 'Devolved multi-tasking hierarchy', 'night', '90');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('871588165', 'Proactive real-time standardization', 'day', '31');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('297280744', 'Extended discrete structure', 'night', '86');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('114512262', 'Multi-tiered logistical installation', 'day', '72');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('512208165', 'Business-focused value-added paradigm', 'day', '29');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('720694240', 'Progressive value-added structure', 'night', '19');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('501911381', 'Multi-layered web-enabled moderator', 'night', '94');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('511009464', 'Optional optimal superstructure', 'night', '21');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('958915878', 'Devolved 6th generation encoding', 'day', '36');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('191042409', 'Mandatory executive encoding', 'night', '17');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('646705798', 'Face to face zero tolerance synergy', 'night', '84');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('969174273', 'Devolved holistic core', 'day', '64');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('291285237', 'Multi-channelled asynchronous interface', 'night', '5');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('372889490', 'Enterprise-wide methodical middleware', 'night', '82');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('650278722', 'Implemented systemic policy', 'night', '26');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('452149422', 'Configurable didactic conglomeration', 'day', '12');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('384936340', 'Profound optimal middleware', 'day', '68');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('397374856', 'Phased next generation application', 'day', '84');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('498562736', 'Future-proofed clear-thinking firmware', 'day', '39');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('425324585', 'Synergistic 4th generation benchmark', 'night', '93');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('410806769', 'Diverse next generation success', 'night', '18');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('796418068', 'Front-line interactive process improvement', 'day', '74');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('348335479', 'Exclusive needs-based framework', 'day', '90');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('36639767', 'Future-proofed 4th generation array', 'night', '99');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('252916150', 'Progressive coherent function', 'night', '97');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('625565488', 'Operative maximized internet solution', 'night', '4');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('979824245', 'Switchable asymmetric process improvement', 'day', '9');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('195466228', 'Configurable system-worthy initiative', 'night', '6');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('275999006', 'Exclusive 5th generation projection', 'night', '67');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('282738587', 'User-centric transitional hub', 'night', '18');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('672292131', 'Focused empowering firmware', 'day', '28');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('791861596', 'Public-key bottom-line complexity', 'night', '34');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('266455852', 'Enhanced fault-tolerant installation', 'day', '36');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('454526167', 'Streamlined transitional Graphic Interface', 'day', '83');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('510793459', 'Inverse static structure', 'night', '95');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('316109471', 'Proactive multi-tasking encoding', 'day', '83');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('605070887', 'Team-oriented mission-critical access', 'night', '67');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('443953141', 'Horizontal didactic portal', 'night', '93');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('491748097', 'Open-architected 24/7 groupware', 'night', '18');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('103820939', 'Re-contextualized transitional system engine', 'night', '27');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('565437581', 'Exclusive fault-tolerant hierarchy', 'day', '26');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('560250371', 'Future-proofed national strategy', 'day', '12');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('794562734', 'Reactive mission-critical parallelism', 'day', '47');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('627074711', 'Re-engineered regional function', 'day', '36');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('434213558', 'Self-enabling global help-desk', 'day', '53');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('251320838', 'Reduced optimizing throughput', 'night', '7');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('158011562', 'Adaptive human-resource workforce', 'day', '82');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('684491974', 'Mandatory responsive project', 'night', '75');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('273980155', 'Distributed incremental orchestration', 'night', '23');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('297019596', 'Total non-volatile encryption', 'day', '45');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('491404055', 'Open-architected bandwidth-monitored monitoring', 'night', '56');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('989623269', 'Re-contextualized incremental strategy', 'night', '43');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('973093652', 'Fundamental interactive collaboration', 'night', '51');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('326243749', 'Horizontal composite standardization', 'day', '77');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('968445241', 'Proactive mission-critical data-warehouse', 'night', '72');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('727426208', 'Persistent 24/7 budgetary management', 'night', '8');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('153760926', 'Visionary optimal function', 'day', '24');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('735130997', 'Virtual tertiary software', 'night', '18');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('631124025', 'Reactive cohesive secured line', 'night', '44');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('262305060', 'Digitized systematic frame', 'night', '23');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('457261793', 'Progressive clear-thinking architecture', 'day', '51');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('263098272', 'Phased object-oriented encoding', 'night', '42');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('848360444', 'Reduced background service-desk', 'night', '20');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('950747566', 'Triple-buffered foreground internet solution', 'day', '84');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('818253844', 'Triple-buffered intermediate standardization', 'night', '53');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('452771414', 'Re-engineered tertiary definition', 'day', '48');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('762122865', 'Centralized encompassing Graphic Interface', 'day', '44');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('117896298', 'Centralized systematic functionalities', 'night', '69');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('662508701', 'Persistent mission-critical model', 'day', '38');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('578775857', 'Proactive actuating support', 'day', '97');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('351823102', 'Optional multi-tasking contingency', 'day', '82');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('264786699', 'Cross-platform leading edge synergy', 'night', '76');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('250239474', 'Business-focused fresh-thinking projection', 'night', '45');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('767893852', 'Seamless regional knowledge user', 'day', '78');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('724682094', 'Synchronised background system engine', 'day', '14');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('303936143', 'Quality-focused radical challenge', 'night', '46');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('316029782', 'Reactive 3rd generation synergy', 'night', '71');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('502836559', 'Object-based background artificial intelligence', 'day', '84');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('120659878', 'Self-enabling global data-warehouse', 'day', '65');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('288983289', 'Re-engineered bandwidth-monitored monitoring', 'night', '42');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('455705057', 'Enterprise-wide 5th generation hub', 'day', '2');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('646197685', 'Ameliorated needs-based collaboration', 'night', '57');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('678847421', 'User-centric holistic solution', 'night', '8');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('353457164', 'Assimilated value-added paradigm', 'night', '17');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('254789599', 'Synergistic asymmetric encryption', 'day', '77');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('269348398', 'Reverse-engineered optimal concept', 'day', '14');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('281895850', 'Profit-focused holistic forecast', 'night', '73');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('290039867', 'Assimilated encompassing definition', 'night', '43');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('320067392', 'De-engineered scalable contingency', 'night', '3');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('987940103', 'Up-sized 3rd generation capacity', 'day', '94');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('48629856', 'Configurable foreground implementation', 'night', '94');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('558619479', 'Diverse tertiary help-desk', 'night', '78');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('677164210', 'Customer-focused eco-centric protocol', 'night', '96');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('961968822', 'Networked user-facing instruction set', 'day', '74');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('497662026', 'Operative zero tolerance conglomeration', 'night', '45');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('754532901', 'Front-line asymmetric monitoring', 'day', '96');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('416415481', 'Reduced intermediate workforce', 'night', '18');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('917568682', 'Cross-group asymmetric time-frame', 'day', '70');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('147436143', 'Triple-buffered bottom-line intranet', 'night', '43');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('731990807', 'Open-source optimizing adapter', 'night', '95');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('78290754', 'Multi-tiered intermediate customer loyalty', 'night', '80');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('68935519', 'Organic even-keeled circuit', 'day', '14');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('270206777', 'Distributed optimal attitude', 'day', '32');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('886298799', 'De-engineered asymmetric hardware', 'night', '77');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('537353971', 'Organized multi-tasking alliance', 'day', '27');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('605787062', 'Face to face homogeneous architecture', 'night', '34');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('48889446', 'Optimized bandwidth-monitored emulation', 'night', '42');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('256957550', 'Vision-oriented intermediate circuit', 'night', '59');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('764130356', 'Horizontal asynchronous capability', 'day', '60');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('477966420', 'User-friendly transitional internet solution', 'night', '60');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('515420780', 'Horizontal disintermediate archive', 'day', '14');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('177144597', 'Robust homogeneous definition', 'night', '14');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('220767596', 'Proactive full-range paradigm', 'day', '40');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('93200454', 'Multi-channelled multimedia functionalities', 'night', '39');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('721506696', 'Optimized asymmetric protocol', 'night', '24');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('95160288', 'Profound full-range array', 'night', '77');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('852291133', 'Upgradable non-volatile toolset', 'night', '62');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('52798183', 'Multi-channelled logistical definition', 'day', '44');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('248543101', 'Configurable multi-state moderator', 'day', '25');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('834185361', 'Adaptive tangible open architecture', 'day', '2');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('83857247', 'Pre-emptive fresh-thinking throughput', 'day', '48');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('159715817', 'Cross-platform explicit software', 'day', '50');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('790289455', 'Enhanced 24/7 leverage', 'night', '15');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('533857757', 'Diverse explicit matrix', 'day', '8');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('102891735', 'Optional 3rd generation flexibility', 'day', '79');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('189509315', 'Proactive empowering customer loyalty', 'day', '88');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('777666471', 'Fundamental radical complexity', 'day', '76');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('120765029', 'Devolved bottom-line conglomeration', 'night', '80');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('325925804', 'Balanced incremental core', 'night', '10');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('601228657', 'Mandatory needs-based interface', 'night', '17');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('506431182', 'Right-sized static hierarchy', 'night', '10');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('454232859', 'Ergonomic value-added conglomeration', 'day', '96');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('588400392', 'Configurable foreground task-force', 'night', '93');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('830178016', 'Fully-configurable motivating attitude', 'day', '99');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('676399782', 'Grass-roots regional forecast', 'day', '42');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('720762480', 'Assimilated multi-tasking attitude', 'day', '63');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('398134177', 'Inverse heuristic local area network', 'day', '34');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('54962924', 'Triple-buffered well-modulated application', 'day', '31');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('878180163', 'Enterprise-wide systemic middleware', 'night', '20');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('256399714', 'Vision-oriented static collaboration', 'night', '80');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('724326080', 'Innovative systematic solution', 'day', '89');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('762323383', 'Switchable needs-based synergy', 'night', '24');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('71360113', 'Networked explicit hardware', 'day', '43');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('995950397', 'Enterprise-wide mission-critical data-warehouse', 'day', '95');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('484962060', 'Progressive zero tolerance knowledge user', 'day', '76');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('977484807', 'Decentralized radical flexibility', 'night', '27');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('969171457', 'Reactive tertiary protocol', 'night', '32');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('309177026', 'Cloned scalable projection', 'night', '33');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('523490739', 'Reactive clear-thinking interface', 'night', '30');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('563344039', 'User-friendly logistical access', 'day', '56');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('673179407', 'Multi-lateral neutral implementation', 'night', '55');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('560800442', 'Customer-focused fresh-thinking task-force', 'day', '18');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('956130202', 'Seamless maximized analyzer', 'night', '86');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('399975650', 'Vision-oriented empowering framework', 'day', '89');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('630540253', 'Synergized non-volatile intranet', 'night', '45');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('945638121', 'Networked maximized leverage', 'day', '75');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('732895849', 'Operative grid-enabled capacity', 'night', '35');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('571331910', 'Networked tangible model', 'day', '68');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('637619479', 'Digitized mobile framework', 'day', '34');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('105383099', 'Enterprise-wide bifurcated implementation', 'day', '2');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('629214736', 'Multi-channelled clear-thinking function', 'night', '73');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('415114564', 'Enhanced 24 hour initiative', 'day', '24');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('116751453', 'Horizontal discrete conglomeration', 'night', '27');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('924506625', 'Operative multi-state intranet', 'night', '45');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('604854462', 'Polarised optimizing throughput', 'day', '82');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('212248039', 'Advanced optimizing success', 'day', '72');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('401911095', 'Operative demand-driven success', 'day', '89');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('614150741', 'Ameliorated upward-trending help-desk', 'night', '7');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('664863057', 'Seamless maximized productivity', 'night', '41');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('408728062', 'Distributed 3rd generation encoding', 'night', '45');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('827485113', 'Grass-roots hybrid encryption', 'night', '6');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('940434111', 'Upgradable stable protocol', 'day', '44');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('429710231', 'Stand-alone holistic function', 'day', '46');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('966213559', 'Monitored responsive data-warehouse', 'night', '56');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('685971668', 'Integrated object-oriented capacity', 'day', '73');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('484957058', 'Extended real-time superstructure', 'night', '80');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('406586980', 'Operative optimizing capacity', 'night', '54');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('478823934', 'Virtual dynamic success', 'day', '19');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('75274701', 'Advanced scalable firmware', 'night', '58');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('7611223', 'Reverse-engineered secondary matrices', 'night', '5');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('323994824', 'Open-architected exuding migration', 'night', '38');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('796978319', 'Upgradable non-volatile time-frame', 'night', '11');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('491548716', 'Front-line contextually-based encoding', 'night', '47');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('944883125', 'Ergonomic next generation adapter', 'day', '98');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('338679349', 'Optional coherent capacity', 'night', '37');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('236578520', 'Cloned user-facing database', 'day', '100');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('276425571', 'Cross-platform mission-critical help-desk', 'day', '37');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('260709922', 'Multi-tiered bandwidth-monitored success', 'night', '34');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('669092693', 'Visionary 24 hour matrices', 'day', '17');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('589883717', 'Optional uniform flexibility', 'day', '73');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('563850309', 'Profound human-resource matrix', 'night', '63');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('31662405', 'Mandatory user-facing parallelism', 'day', '57');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('885610183', 'Diverse 4th generation definition', 'day', '57');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('351616627', 'Future-proofed 24 hour emulation', 'day', '44');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('767915561', 'Optimized 24 hour orchestration', 'day', '44');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('981731162', 'Profound intermediate policy', 'day', '90');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('948331578', 'Cross-group 24/7 interface', 'day', '63');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('271994382', 'Up-sized homogeneous adapter', 'night', '41');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('184614585', 'Horizontal transitional approach', 'day', '13');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('29351512', 'Re-contextualized leading edge conglomeration', 'night', '38');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('181278948', 'Front-line clear-thinking paradigm', 'night', '70');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('886101710', 'Team-oriented eco-centric initiative', 'day', '95');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('235637368', 'Reduced tertiary encoding', 'night', '60');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('129718459', 'Reactive homogeneous success', 'day', '11');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('1318589', 'Horizontal system-worthy success', 'night', '93');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('82726327', 'Cloned explicit forecast', 'night', '19');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('634297699', 'Object-based human-resource time-frame', 'day', '15');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('320763954', 'Configurable asynchronous superstructure', 'day', '100');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('316509877', 'Grass-roots stable moderator', 'night', '98');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('365123118', 'Implemented coherent emulation', 'day', '91');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('522815774', 'Up-sized next generation open system', 'day', '13');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('584356063', 'Visionary client-driven frame', 'day', '79');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('320412580', 'Versatile stable open system', 'day', '1');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('647987674', 'Monitored user-facing contingency', 'day', '47');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('359992481', 'Future-proofed composite service-desk', 'night', '10');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('312182808', 'Advanced directional concept', 'day', '7');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('29148398', 'Distributed well-modulated workforce', 'night', '54');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('440520247', 'Synergistic regional infrastructure', 'night', '33');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('503611751', 'Vision-oriented eco-centric model', 'day', '39');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('631556122', 'Intuitive hybrid service-desk', 'night', '4');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('321046457', 'Grass-roots 5th generation complexity', 'day', '55');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('523788257', 'Horizontal holistic paradigm', 'night', '66');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('483933956', 'Extended background archive', 'night', '27');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('662800320', 'Virtual foreground attitude', 'night', '30');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('705918990', 'Horizontal radical interface', 'day', '40');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('830729827', 'Seamless 4th generation methodology', 'day', '43');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('239792665', 'Grass-roots mission-critical help-desk', 'night', '59');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('301098231', 'Advanced background customer loyalty', 'night', '92');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('873523688', 'Implemented local algorithm', 'night', '80');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('232986373', 'Down-sized motivating model', 'day', '54');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('208926740', 'Customizable bifurcated encoding', 'night', '77');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('754927059', 'Distributed context-sensitive concept', 'day', '31');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('385139046', 'Synchronised context-sensitive customer loyalty', 'day', '63');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('199028700', 'Synergistic composite capacity', 'night', '95');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('367296024', 'Fundamental zero tolerance collaboration', 'day', '90');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('364637863', 'Team-oriented national adapter', 'day', '14');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('994191941', 'Optional responsive encoding', 'night', '39');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('851678274', 'Horizontal context-sensitive attitude', 'day', '26');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('131972700', 'Object-based next generation migration', 'night', '25');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('245965063', 'Configurable human-resource extranet', 'night', '3');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('145303760', 'Visionary eco-centric frame', 'day', '97');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('944664825', 'Phased solution-oriented secured line', 'day', '86');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('961676191', 'Function-based exuding methodology', 'night', '53');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('264918397', 'Function-based leading edge open system', 'day', '20');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('695811601', 'Function-based uniform alliance', 'day', '37');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('658839364', 'Open-architected optimal capability', 'day', '75');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('40689201', 'Self-enabling modular attitude', 'day', '21');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('611217353', 'Synergized eco-centric application', 'day', '22');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('436419950', 'Fundamental local open architecture', 'day', '95');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('399588157', 'Team-oriented bottom-line paradigm', 'night', '19');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('256678902', 'Decentralized local website', 'night', '21');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('439785299', 'Seamless zero administration definition', 'night', '99');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('51986216', 'Networked multi-tasking implementation', 'night', '7');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('119304352', 'Cloned stable policy', 'day', '42');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('235132438', 'Seamless heuristic analyzer', 'night', '39');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('653484857', 'Focused context-sensitive throughput', 'day', '9');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('48156025', 'Programmable bifurcated middleware', 'day', '87');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('51259587', 'Front-line stable solution', 'day', '30');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('343062344', 'Synergized zero administration array', 'day', '55');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('104614512', 'Profound bi-directional core', 'night', '81');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('811963473', 'Reverse-engineered transitional algorithm', 'night', '40');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('805916862', 'Future-proofed didactic framework', 'night', '52');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('75098009', 'Assimilated eco-centric firmware', 'day', '1');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('19224440', 'Enterprise-wide actuating conglomeration', 'night', '36');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('954908799', 'Multi-tiered discrete infrastructure', 'day', '47');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('699375490', 'Grass-roots mission-critical system engine', 'day', '96');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('135966803', 'Organized analyzing process improvement', 'night', '32');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('144530622', 'Organic global adapter', 'day', '1');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('75332902', 'Digitized clear-thinking budgetary management', 'night', '42');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('617027978', 'Open-source motivating process improvement', 'day', '90');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('654669738', 'Visionary intangible strategy', 'day', '35');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('582697137', 'Balanced foreground instruction set', 'day', '58');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('952241063', 'Cross-group zero administration artificial intelligence', 'night', '69');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('161238259', 'Multi-channelled tertiary firmware', 'night', '17');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('728898239', 'Expanded asymmetric architecture', 'night', '89');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('651266013', 'Quality-focused mobile concept', 'day', '30');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('683660953', 'Networked human-resource info-mediaries', 'night', '27');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('925594582', 'Optional system-worthy approach', 'night', '85');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('462866727', 'Balanced tangible challenge', 'night', '53');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('977115838', 'Configurable non-volatile parallelism', 'night', '52');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('783657761', 'Total actuating analyzer', 'day', '53');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('157124583', 'Synergistic high-level complexity', 'day', '44');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('895152183', 'Programmable directional matrix', 'day', '19');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('758123676', 'Persistent analyzing definition', 'day', '1');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('371959453', 'Future-proofed well-modulated infrastructure', 'day', '23');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('393211634', 'Persevering bi-directional data-warehouse', 'night', '46');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('885381480', 'Programmable disintermediate infrastructure', 'day', '30');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('266060634', 'Reactive modular archive', 'day', '45');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('337469789', 'Open-architected national system engine', 'day', '38');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('204547025', 'Realigned radical emulation', 'day', '74');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('370058723', 'Extended maximized protocol', 'night', '72');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('428855412', 'Proactive bi-directional installation', 'day', '89');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('719927297', 'Innovative discrete project', 'night', '84');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('271629369', 'Grass-roots secondary attitude', 'day', '83');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('416258111', 'Inverse asymmetric hierarchy', 'night', '18');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('160928250', 'Digitized exuding paradigm', 'night', '13');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('311878721', 'Open-architected 4th generation projection', 'day', '23');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('420667104', 'Cloned actuating model', 'day', '2');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('574160198', 'Customer-focused 6th generation core', 'night', '62');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('7637888', 'Fully-configurable contextually-based time-frame', 'day', '83');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('120784106', 'Networked exuding alliance', 'day', '24');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('932658722', 'De-engineered zero administration artificial intelligence', 'night', '73');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('614140679', 'Front-line 3rd generation neural-net', 'night', '21');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('861694141', 'Automated multi-state matrix', 'day', '57');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('643568623', 'Mandatory value-added internet solution', 'day', '73');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('220470040', 'Innovative neutral toolset', 'night', '25');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('130595066', 'Programmable contextually-based matrices', 'night', '92');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('391809055', 'Re-engineered grid-enabled access', 'night', '22');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('448229932', 'Ergonomic global encoding', 'day', '44');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('278190259', 'Automated eco-centric emulation', 'night', '92');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('39404276', 'Right-sized leading edge application', 'night', '19');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('950912477', 'Open-architected context-sensitive array', 'night', '23');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('216624276', 'Open-source well-modulated archive', 'night', '57');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('316559115', 'Optimized high-level system engine', 'day', '22');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('533101215', 'Multi-channelled explicit archive', 'night', '10');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('396683452', 'Multi-lateral exuding middleware', 'day', '10');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('971242502', 'User-centric tertiary implementation', 'day', '90');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('226748639', 'Organized web-enabled analyzer', 'day', '34');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('186127423', 'Open-source 5th generation architecture', 'night', '82');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('744113083', 'Managed hybrid methodology', 'night', '36');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('223840340', 'Exclusive content-based alliance', 'day', '9');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('358808725', 'Networked 4th generation synergy', 'night', '96');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('116556123', 'Centralized impactful benchmark', 'day', '60');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('69805396', 'Triple-buffered secondary workforce', 'day', '86');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('696212058', 'Implemented secondary ability', 'night', '55');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('754081554', 'Reduced radical array', 'night', '72');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('159288937', 'Monitored bifurcated function', 'night', '57');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('240185478', 'Up-sized interactive pricing structure', 'day', '45');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('777531034', 'Phased reciprocal protocol', 'day', '64');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('401453910', 'Customizable non-volatile internet solution', 'night', '96');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('324374313', 'Re-contextualized transitional project', 'day', '60');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('702335586', 'Intuitive 4th generation matrices', 'day', '47');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('51375486', 'Networked stable capacity', 'day', '17');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('624950301', 'Upgradable local artificial intelligence', 'night', '62');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('731586585', 'Visionary methodical encoding', 'night', '42');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('816895966', 'Customer-focused content-based data-warehouse', 'day', '23');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('606206291', 'Programmable content-based open system', 'night', '33');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('236305360', 'Re-contextualized content-based flexibility', 'night', '86');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('423970262', 'Balanced intangible approach', 'night', '34');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('544657882', 'Open-architected non-volatile system engine', 'night', '22');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('377675567', 'Organic uniform local area network', 'night', '93');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('844037393', 'Organized foreground artificial intelligence', 'day', '8');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('58377538', 'Multi-lateral scalable definition', 'day', '7');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('353534950', 'User-centric foreground open system', 'day', '9');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('717935012', 'Re-engineered multimedia capacity', 'day', '80');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('460689155', 'Pre-emptive 3rd generation workforce', 'night', '70');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('204871125', 'Grass-roots leading edge infrastructure', 'night', '43');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('400784468', 'Vision-oriented regional solution', 'night', '44');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('687084573', 'Upgradable logistical instruction set', 'day', '95');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('386233896', 'Secured 5th generation moderator', 'night', '3');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('146001764', 'Intuitive client-driven support', 'day', '93');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('865619071', 'Implemented asymmetric emulation', 'day', '4');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('393253949', 'Grass-roots foreground definition', 'night', '50');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('47988523', 'Configurable encompassing circuit', 'night', '20');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('972336296', 'Multi-channelled fault-tolerant budgetary management', 'day', '8');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('864285533', 'Innovative solution-oriented interface', 'night', '33');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('96089641', 'Optimized local strategy', 'night', '33');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('604661820', 'Enterprise-wide contextually-based strategy', 'day', '42');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('969959695', 'Right-sized logistical contingency', 'day', '66');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('976695730', 'Profound contextually-based local area network', 'night', '74');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('673861904', 'Expanded empowering knowledge user', 'night', '15');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('847728775', 'Networked empowering moratorium', 'night', '39');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('761190264', 'User-centric full-range protocol', 'night', '8');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('112936862', 'Public-key regional architecture', 'day', '23');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('568087678', 'Implemented optimizing knowledge base', 'day', '10');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('305062534', 'Sharable multi-tasking analyzer', 'day', '29');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('931123794', 'Visionary 24 hour functionalities', 'day', '99');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('376690460', 'Switchable zero defect database', 'day', '9');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('572881013', 'Devolved value-added attitude', 'night', '95');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('724169472', 'User-friendly dynamic orchestration', 'night', '12');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('679906405', 'Optional neutral system engine', 'night', '26');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('371008910', 'Upgradable 3rd generation open system', 'day', '97');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('173955839', 'Networked upward-trending utilisation', 'night', '59');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('656958707', 'Self-enabling even-keeled budgetary management', 'day', '31');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('260371853', 'Ergonomic incremental budgetary management', 'night', '84');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('306886371', 'Proactive logistical infrastructure', 'day', '17');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('103478442', 'Robust analyzing migration', 'day', '44');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('684807629', 'Decentralized context-sensitive task-force', 'night', '15');
INSERT INTO nurse (id_number, specialization, shift_type, department_number) VALUES ('870188525', 'Switchable demand-driven moratorium', 'day', '28');
