INSERT INTO medication (medication_code, medication_name, price) VALUES ('ZIQ0469', 'luctus tincidunt', '596.58');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('GM714', 'nulla', '102.76');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('UA859', 'lacinia eget', '244.36');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('UZF58735', 'nisi vulputate nonummy', '896.02');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('AIDT821', 'nascetur ridiculus mus etiam', '391.3');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('DQLW221', 'tortor id', '767.54');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('WKKLD62847', 'vel', '482.5');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('JG2523', 'congue risus semper porta volutpat', '988.52');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('RSTA22808', 'hac habitasse platea dictumst', '342.15');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('XOJ42657', 'pretium quis lectus', '214.68');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('QPHR07586', 'odio cras mi pede', '495.61');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('FZ067', 'id', '430.81');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('LEOMZ8609', 'quisque', '482.11');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('QP7388', 'pellentesque', '63.43');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('TB7902', 'vivamus', '134.74');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('KNL17162', 'ut at dolor quis odio', '286.08');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('TFSS958', 'ullamcorper augue a suscipit nulla', '118.64');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('DW112', 'diam id ornare imperdiet', '523.66');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('RLBID8580', 'sit amet nulla quisque arcu', '634.71');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('ES3435', 'orci luctus et ultrices', '191.47');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('RTQSN07500', 'ultrices posuere cubilia curae mauris', '709.1');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('PDES2464', 'ligula', '992.02');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('BYTHZ03238', 'quam fringilla rhoncus', '791.14');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('JSZB43405', 'diam', '57.79');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('OT98471', 'venenatis lacinia aenean sit amet', '940.45');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('GFCOC584', 'in lectus pellentesque', '104.56');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('NJ9933', 'justo sollicitudin ut suscipit a', '529.72');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('QWBFJ33831', 'pulvinar lobortis est', '123.49');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('DZLKH43141', 'facilisi cras non velit', '343.23');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('QL6304', 'nunc proin at turpis a', '178.56');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('KOTN7668', 'justo in blandit ultrices enim', '991.72');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('TOJOF858', 'ac nibh fusce', '879.45');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('ETH622', 'elementum ligula vehicula consequat', '685.91');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('QAFI674', 'felis', '549.28');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('LH8117', 'montes', '989.9');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('ZZRB1122', 'ultrices enim lorem ipsum dolor', '980.52');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('SC4908', 'non ligula pellentesque', '248.45');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('FQESX57214', 'commodo vulputate justo', '490.65');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('TACEF0720', 'aliquam lacus morbi', '825.86');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('YS7333', 'lobortis sapien sapien', '107.74');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('ZP7882', 'convallis nulla', '735.9');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('ARZ3433', 'tristique', '180.55');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('CBES170', 'quis turpis eget elit', '338.39');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('OOOK044', 'leo odio condimentum id luctus', '793.76');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('TPRT62726', 'a feugiat et eros', '230.48');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('QTJ00351', 'luctus et', '354.7');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('ZVOMV44079', 'turpis', '866.54');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('HI553', 'nullam molestie nibh in lectus', '230.31');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('OLI740', 'habitasse platea', '917.41');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('LDV19608', 'eu interdum eu', '426.62');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('WGBZM912', 'pellentesque', '691.9');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('HFK1270', 'morbi non quam nec dui', '180.74');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('BQT949', 'nulla', '403.19');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('ZUKB62773', 'curae', '260.59');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('VJRR473', 'et ultrices posuere', '766.82');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('JQHBP942', 'sit amet turpis', '93.38');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('WQA352', 'lobortis vel dapibus at', '711.79');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('JLSLC8931', 'dapibus augue vel accumsan tellus', '197.73');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('QTXH430', 'magna vestibulum aliquet ultrices', '17.96');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('GXRWP8827', 'quis orci', '593.56');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('QK58586', 'lorem', '675.65');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('MEAB0329', 'eget', '355.13');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('ATQG5672', 'duis ac', '323.6');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('EVYY258', 'luctus rutrum nulla tellus in', '959.97');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('DNT30654', 'augue vestibulum rutrum rutrum', '667.87');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('MJ6922', 'neque vestibulum eget vulputate', '375.03');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('CBKS6392', 'mauris lacinia sapien quis', '716.82');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('PVDP1159', 'arcu', '340.12');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('BUHL84806', 'sed', '812.18');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('SKSL27482', 'aenean fermentum donec ut', '258.05');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('RS04925', 'dictumst aliquam augue quam', '724.6');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('IMDQM9434', 'adipiscing lorem', '447.75');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('DAH47752', 'enim lorem ipsum', '950.05');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('AC4396', 'congue elementum in hac habitasse', '120.93');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('AKP23361', 'vel', '427.02');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('ROEW486', 'bibendum', '674.64');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('IJEN4614', 'vestibulum', '890.1');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('METD10077', 'mi pede malesuada', '637.5');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('GSR96319', 'lorem', '880.64');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('LLMKN946', 'integer tincidunt ante vel ipsum', '441.57');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('IHS006', 'non interdum', '755.86');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('EYTKP879', 'est risus auctor sed', '91.46');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('DPMMH7779', 'mi sit amet lobortis', '339.24');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('NQB80316', 'vestibulum ante ipsum primis', '86.02');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('FF91572', 'ipsum', '592.23');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('ARBFO072', 'nonummy integer non velit donec', '28.58');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('MOWTD6442', 'ultricies', '985.72');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('TK71257', 'blandit nam nulla integer pede', '184.83');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('LP4598', 'sapien cum sociis', '65.31');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('AZPX0649', 'donec pharetra magna', '377.43');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('BQ08709', 'condimentum curabitur', '893.94');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('ECW498', 'et ultrices posuere cubilia curae', '176.46');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('PEJ538', 'nullam sit', '891.5');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('GS308', 'sollicitudin vitae consectetuer eget rutrum', '547.78');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('BLBEJ697', 'primis', '465.93');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('YXM2704', 'quis tortor id nulla', '476.23');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('XULH3351', 'cras', '192.16');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('ETH433', 'accumsan tellus', '911.82');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('LDRVH7154', 'ipsum', '327.58');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('RVDIM91661', 'montes nascetur ridiculus mus', '892.45');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('CD77267', 'eget congue eget', '788.2');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('SCILI31009', 'mi in', '967.24');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('OE66765', 'cras', '584.72');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('OB9788', 'sed vestibulum sit amet', '661.23');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('CX58269', 'viverra dapibus nulla suscipit', '64.81');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('CSWL6144', 'maecenas tincidunt lacus at velit', '252.05');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('UKDQ5011', 'amet nunc viverra', '291.77');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('MAE3288', 'laoreet ut rhoncus', '600.99');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('BP7602', 'cursus urna ut', '127.49');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('VB74080', 'lorem ipsum dolor sit amet', '593.28');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('PR406', 'morbi', '340.01');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('UI6627', 'odio donec', '111.49');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('LVNDS449', 'nulla quisque arcu', '129.9');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('PXGY4872', 'vestibulum sed magna at nunc', '427.51');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('CZHQL360', 'dis parturient montes nascetur', '754.66');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('FOW4572', 'quam', '521.0');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('LC2009', 'accumsan felis ut', '635.09');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('ZK8579', 'blandit lacinia erat', '474.73');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('PR5832', 'vitae nisl aenean lectus pellentesque', '128.18');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('MQSG6306', 'nunc commodo placerat', '36.7');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('JEHW3219', 'pede justo eu massa', '145.76');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('RUFBT615', 'praesent blandit lacinia erat vestibulum', '415.65');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('ULOUX022', 'morbi', '851.7');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('XYH75370', 'non velit donec', '579.38');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('ARE760', 'ut at dolor quis odio', '156.84');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('PLFV086', 'luctus et', '183.82');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('XMQ407', 'eros elementum pellentesque', '253.01');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('LGD2002', 'mi integer ac', '444.15');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('DYNFG6787', 'vestibulum', '569.91');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('XXXKG91544', 'ac', '206.45');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('RXLA557', 'amet erat nulla tempus', '76.92');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('XTL276', 'gravida nisi at nibh', '487.82');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('WS8460', 'libero', '980.61');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('NSCDK34776', 'enim blandit mi', '279.11');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('WVLF22384', 'diam neque vestibulum eget vulputate', '398.72');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('WER0895', 'vestibulum', '787.78');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('GFH3355', 'a feugiat', '715.21');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('JFJ636', 'amet justo morbi ut odio', '676.04');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('TP921', 'a libero nam dui', '537.13');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('KRWEU412', 'ultrices aliquet maecenas', '872.88');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('XIYK000', 'sem', '334.75');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('AKP46106', 'odio', '180.31');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('JSR892', 'suscipit a', '86.58');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('YKKMH892', 'orci pede venenatis non', '210.99');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('ULTO299', 'at turpis a', '157.39');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('JSQ40491', 'sit', '465.57');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('VA121', 'id turpis integer', '965.74');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('PBZI751', 'nam', '380.92');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('FQD4681', 'vel', '774.27');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('XG406', 'at velit eu est congue', '210.26');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('XQ46404', 'leo', '152.54');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('DFZWR1180', 'est et tempus', '100.94');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('OY209', 'nascetur ridiculus mus etiam vel', '150.37');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('RED5512', 'fermentum donec', '854.06');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('XC7229', 'imperdiet et commodo', '145.59');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('ASKS99150', 'orci vehicula condimentum', '270.97');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('WYOF823', 'vitae nisi nam', '146.62');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('KIS1785', 'lorem', '365.99');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('TZVP8201', 'accumsan odio curabitur convallis', '814.99');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('BQYJ4195', 'penatibus', '322.81');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('YCL621', 'odio', '163.3');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('BZPNR65169', 'non', '286.33');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('SFR7539', 'eget eleifend luctus ultricies', '430.94');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('YMOV10632', 'massa id lobortis convallis tortor', '854.92');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('IANM82734', 'erat id mauris vulputate elementum', '726.27');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('NEDM398', 'tellus nulla ut erat', '555.92');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('ZPUS9857', 'curae duis faucibus', '479.77');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('JKRE241', 'elit sodales', '743.97');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('HNHB538', 'dictumst', '820.48');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('RAZ020', 'magna ac', '880.28');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('HAFKL65747', 'in', '603.63');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('DUCT855', 'erat tortor sollicitudin', '465.24');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('KIWU05584', 'at lorem integer tincidunt ante', '728.23');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('CGQ013', 'consequat nulla nisl nunc', '16.44');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('CPTG10318', 'in tempus sit amet', '408.13');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('LSLV6305', 'velit nec nisi', '774.88');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('RY5339', 'platea dictumst', '304.86');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('MKKJ12984', 'primis in faucibus orci luctus', '218.0');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('KBUW978', 'cum sociis', '477.2');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('HQX67818', 'massa volutpat convallis', '583.64');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('GZAO889', 'orci pede venenatis', '991.91');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('MVNGV104', 'cras pellentesque volutpat', '496.17');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('CGUG3475', 'leo maecenas', '659.49');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('FDV17928', 'quis', '960.75');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('MWLX27505', 'non ligula', '345.97');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('APY6251', 'magnis dis parturient montes nascetur', '5.1');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('XXMCC372', 'lacus', '85.32');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('BNEG6253', 'porttitor pede', '851.49');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('ZGNJ700', 'quis augue luctus tincidunt', '422.22');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('WFT461', 'tortor quis turpis sed ante', '485.69');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('NMALG995', 'turpis a', '331.5');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('RKVSN73968', 'tellus', '505.42');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('ZJ830', 'in', '836.46');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('PR1665', 'vulputate vitae nisl aenean lectus', '153.67');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('QFCI1317', 'in faucibus orci', '310.25');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('RNJ34572', 'eget tincidunt eget', '933.31');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('OFSXN8531', 'ornare consequat lectus in est', '11.74');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('QUK77841', 'diam id', '625.98');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('MB3246', 'vivamus', '214.81');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('LTQMI047', 'diam nam', '580.85');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('ONX136', 'erat', '145.0');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('YDFWH928', 'proin at turpis a pede', '172.04');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('CNND198', 'neque vestibulum eget vulputate ut', '774.98');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('CC03527', 'lacinia aenean', '697.23');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('HGATP035', 'semper sapien a', '457.94');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('BQTGN0399', 'nec', '281.75');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('QLO350', 'orci luctus et ultrices', '476.67');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('OV644', 'curabitur at ipsum', '433.46');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('RM64006', 'nec condimentum neque sapien', '696.24');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('SP96043', 'dui vel sem', '231.93');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('SLU7441', 'ac leo', '54.88');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('BA2517', 'sed', '394.33');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('LS64027', 'nam ultrices libero non', '602.4');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('JDRBC6950', 'porttitor id consequat in consequat', '793.8');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('NC8684', 'in eleifend', '908.3');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('CEE11457', 'in hac habitasse platea', '688.99');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('LADDC07603', 'non mauris', '399.91');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('AM26032', 'metus', '564.78');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('RAO2251', 'vestibulum proin eu mi nulla', '645.83');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('QQ57608', 'risus', '802.78');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('JQFG155', 'orci mauris lacinia sapien', '349.99');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('VGD6134', 'justo pellentesque', '793.27');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('EA7045', 'luctus et ultrices posuere', '199.98');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('IELJ98857', 'purus phasellus in felis donec', '27.37');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('YZPK151', 'dolor sit amet', '606.85');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('WXSZ79315', 'quis lectus suspendisse', '734.74');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('EXYWR1045', 'ante', '624.48');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('NM600', 'lacinia sapien quis libero', '64.25');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('MPXY45731', 'congue vivamus metus', '581.93');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('TIB042', 'vulputate justo in blandit', '380.81');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('APDGS4079', 'nibh in', '540.86');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('QVMAX135', 'nisl venenatis lacinia aenean sit', '984.71');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('TVMKN9451', 'pede posuere nonummy integer', '562.93');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('LV64418', 'a ipsum integer a nibh', '326.35');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('RNU105', 'et magnis dis', '453.95');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('TXX9033', 'ut tellus', '237.89');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('CDKFT8419', 'vivamus tortor', '264.17');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('GHWUR594', 'ut', '520.3');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('OY53489', 'duis', '853.63');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('ORR772', 'justo sit amet', '82.98');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('OFB3859', 'quisque', '826.8');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('IHVXT9596', 'nullam varius nulla facilisi cras', '818.48');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('BJC1634', 'ante', '761.78');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('IVOIF36841', 'sed lacus morbi sem mauris', '713.5');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('WC3937', 'dui vel sem sed', '371.85');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('YSNS201', 'bibendum morbi non quam', '588.53');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('GR3832', 'quis orci', '128.09');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('ZNZQ876', 'semper', '780.98');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('QDA084', 'aliquet ultrices erat tortor sollicitudin', '404.13');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('MVMAC123', 'habitasse platea dictumst', '801.93');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('TFNLF66441', 'integer a nibh in quis', '666.77');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('TCDD411', 'sollicitudin vitae consectetuer eget', '550.36');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('PRZ53731', 'nulla facilisi cras non velit', '634.05');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('KCMTX5187', 'et commodo vulputate', '714.04');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('RKYSC3536', 'consequat nulla nisl nunc', '949.73');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('DO8214', 'id mauris vulputate elementum', '690.8');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('RUEAV1547', 'volutpat sapien arcu', '610.97');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('OMP3422', 'sapien quis libero nullam', '667.32');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('AC2976', 'porta volutpat erat quisque', '763.88');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('IPA27417', 'in hac habitasse platea', '181.22');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('RHAA9775', 'est phasellus sit amet erat', '211.14');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('HF633', 'dolor morbi vel', '35.39');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('JPJT373', 'pulvinar lobortis est phasellus sit', '482.89');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('OV50337', 'in sapien iaculis congue', '492.34');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('YHB28083', 'nulla ultrices', '976.58');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('KAFBZ60622', 'orci pede venenatis non', '810.43');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('PS6055', 'enim', '634.96');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('WN78213', 'pede', '391.47');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('VIKP5447', 'elit proin risus praesent', '411.37');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('PACP324', 'sapien urna pretium', '843.86');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('AOL84401', 'et', '889.23');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('LMAFT70355', 'morbi', '935.65');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('ACV10502', 'quis odio consequat varius', '453.39');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('MW63539', 'ornare consequat lectus in', '44.97');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('YIDD698', 'justo maecenas', '497.16');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('DUOS01044', 'justo lacinia eget tincidunt', '674.91');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('AEJHC17324', 'tortor sollicitudin mi sit amet', '448.28');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('UM66095', 'pretium', '624.85');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('CN945', 'a', '220.47');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('NMZH54296', 'elementum pellentesque quisque porta', '817.88');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('AE981', 'ipsum primis in', '590.33');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('EUA2594', 'quis', '977.47');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('KI6021', 'libero', '932.81');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('ZCR58132', 'nulla tellus', '273.54');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('DBNEY255', 'nunc commodo', '816.5');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('QIRX39326', 'rhoncus mauris enim', '305.39');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('UCQ365', 'quisque ut erat curabitur gravida', '220.98');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('XSP459', 'vel', '868.23');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('PGT54562', 'ipsum', '813.51');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('TW259', 'varius ut blandit non interdum', '907.21');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('NCKJ28428', 'sit amet sapien dignissim vestibulum', '95.68');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('NXI44651', 'ut rhoncus aliquet', '853.94');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('EEZ0177', 'cras non velit', '949.66');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('QDF5126', 'lobortis vel', '37.32');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('AMWIR4738', 'ut', '852.33');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('XI525', 'diam', '300.86');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('XC659', 'dictumst maecenas ut massa quis', '771.18');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('BXFY083', 'libero nullam', '832.2');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('FH32228', 'posuere nonummy', '31.97');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('WNV90973', 'in felis eu sapien cursus', '851.85');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('VLYXL409', 'eu magna', '220.62');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('PXMU83353', 'amet', '403.48');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('EMBT4551', 'in tempor', '919.17');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('SBQS2996', 'id turpis integer', '781.2');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('RBYOT6072', 'sit', '959.25');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('OMQH658', 'ut odio', '135.29');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('BT28694', 'elit proin risus praesent', '345.37');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('LET51801', 'ante ipsum primis', '349.53');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('JPWI4931', 'mauris sit', '335.31');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('TMLAU384', 'in congue', '813.43');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('MBS327', 'in lectus pellentesque at', '735.71');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('PZDT85288', 'nunc proin', '188.63');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('SQKOR1052', 'congue', '440.5');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('DKDXI91422', 'augue vel accumsan tellus nisi', '860.38');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('UZBQ87836', 'elementum nullam varius nulla facilisi', '830.02');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('DI123', 'ullamcorper purus sit', '13.06');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('GXUD633', 'blandit', '204.11');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('IWS89770', 'id consequat in consequat ut', '192.85');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('UNBN671', 'neque sapien', '589.28');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('YPGK5627', 'vel lectus in quam', '400.39');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('FALL684', 'sapien quis libero', '107.42');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('XMKTX07652', 'ante ipsum primis', '923.79');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('JO4766', 'magna vulputate', '119.59');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('KPBUT16347', 'viverra eget congue', '213.41');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('IQKNO5044', 'lorem', '324.52');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('PHO34503', 'nulla sed vel enim', '567.74');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('ENTS8648', 'lorem vitae mattis nibh ligula', '860.21');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('IOVY29014', 'vulputate', '917.24');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('AVXE175', 'vel lectus in', '783.71');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('VHAEG480', 'ut massa quis augue', '400.79');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('JND367', 'non lectus aliquam sit', '997.13');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('WPCWF45030', 'eu nibh quisque id', '401.5');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('TU395', 'sapien cum sociis natoque', '793.81');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('ZNID7981', 'pede', '668.69');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('PT61753', 'luctus et', '786.37');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('OHQ17971', 'dolor', '212.98');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('BDO3214', 'in ante vestibulum', '241.24');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('RXAZE683', 'platea', '465.23');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('WPHTR4207', 'leo rhoncus', '318.57');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('HC6687', 'convallis eget eleifend', '965.21');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('DJ50013', 'vulputate nonummy maecenas', '375.31');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('YQDL198', 'consequat in consequat ut nulla', '813.69');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('RAV2150', 'nibh fusce lacus purus', '639.99');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('MSOE259', 'nonummy', '641.22');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('NAQO093', 'est', '57.62');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('VPCY5511', 'est donec odio', '956.11');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('VBJGW6356', 'semper interdum mauris', '135.39');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('TMAS1535', 'convallis nunc proin', '416.13');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('XRCHQ12704', 'cras mi pede', '380.04');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('UD2088', 'ipsum', '183.44');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('PQ6836', 'bibendum imperdiet nullam orci pede', '34.05');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('MD73042', 'convallis tortor', '426.6');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('WR469', 'donec odio', '718.19');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('PTGKP8027', 'at nulla suspendisse potenti', '586.9');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('UMO0967', 'eros suspendisse accumsan', '79.31');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('CH3320', 'pellentesque', '611.9');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('MZ2299', 'id massa id nisl venenatis', '264.91');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('DDMLR765', 'sapien non mi integer ac', '192.73');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('XR5115', 'metus aenean', '788.44');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('NGDAU82556', 'ut', '730.88');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('SXD2647', 'ultrices erat', '567.43');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('ZT43800', 'consectetuer eget', '836.65');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('STYN47127', 'augue luctus tincidunt nulla', '60.72');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('QC90756', 'id sapien in', '767.82');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('PZ75837', 'mauris sit amet eros', '890.38');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('SGRDU961', 'amet consectetuer', '849.68');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('FKLVK328', 'orci', '249.58');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('IBKRH60619', 'tortor', '29.14');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('QTMJK399', 'massa id lobortis convallis', '346.94');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('NTO7700', 'sed', '661.29');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('WPNAD021', 'non mi', '409.53');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('CXS523', 'amet justo morbi ut odio', '710.13');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('YK04970', 'pellentesque ultrices mattis odio donec', '626.8');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('FKU44416', 'sapien cursus vestibulum proin', '282.4');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('CRWS47868', 'ante', '613.38');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('YXK627', 'quisque erat eros viverra', '213.49');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('NMBHI61002', 'cubilia curae nulla dapibus dolor', '638.95');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('NUMQ11749', 'arcu libero rutrum', '511.09');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('ES818', 'at nibh in hac habitasse', '649.73');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('CTE7124', 'massa quis augue', '816.08');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('JIPEB96765', 'non mauris', '350.94');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('IUEAG7907', 'pulvinar sed nisl', '736.41');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('NKU7677', 'aliquam augue', '602.77');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('UUMPU5713', 'velit id pretium iaculis diam', '891.24');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('RTSNT26647', 'ipsum primis in faucibus orci', '841.16');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('ITNTT8498', 'eget vulputate ut ultrices', '588.31');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('LDD561', 'volutpat dui', '841.87');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('ZR354', 'ultrices posuere', '586.72');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('UUSX97054', 'rutrum at lorem integer', '395.93');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('EH0667', 'lacinia aenean sit amet justo', '828.98');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('QK02517', 'ac nibh', '891.81');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('LIV321', 'non lectus', '850.12');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('MZEEQ62120', 'at', '287.94');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('MQW86736', 'vestibulum rutrum rutrum neque', '199.25');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('GR23264', 'luctus nec molestie sed justo', '135.84');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('UQ715', 'pellentesque eget nunc donec', '340.6');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('WBQY737', 'integer ac leo pellentesque', '353.22');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('QCCF80992', 'et', '253.45');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('SQS7784', 'lobortis vel', '493.82');
INSERT INTO medication (medication_code, medication_name, price) VALUES ('PW883', 'duis consequat', '740.49');
